---
title: "data_tidying"
author: "Jian Li"
date: "11/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=F, message=F}
library(dplyr)
library(tidyr)
```

# Read and clean data
```{r}
catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method="libcurl"), stringsAsFactors = FALSE)
#head(catch_original)
```

Remove 'all' column and 'notes' column because we don't need them.
```{r}
  catch_data <- catch_original %>% 
    select(-All, -notesRegCode)
```

# Fix Chinook column
Use 'mutate' to fix the column, as it contains non-numeric values

```{r}
  catch_clean <- catch_data %>%
    mutate(Chinook = ifelse(Chinook=="I", 1, Chinook)) %>%
    mutate(Chinook = as.numeric(Chinook))
#    mutate(chinook = as.numeric(Chinook))
```
# Find rows being turned into NA
#```{r}
#  i <- which(is.na(catch_clean$chinook))
#  i
#```

# Reshape data
```{r}
  catch_long <- catch_clean %>%
    pivot_longer(cols=-c(Region, Year), 
                names_to = "Species",
                values_to = "Count")
  head(catch_long)
```

```{r}
  catch_wide <- catch_long %>%
    pivot_wider(names_from = Year,
                values_from = Count)
  head(catch_wide)
```

'rename' Count column to 'catch_thousand'
```{r}
  catch_long <- catch_long %>%
    rename(catch_thousand = Count) %>%
    mutate(catch = catch_thousand * 1000) %>%
    select(-catch_thousand)
  head(catch_long)
```

# Summarize data

```{r}
  mean_region <- catch_long %>%
  group_by(Species) %>%
  summarize(total_catch=sum(catch), catch_mean = mean(catch), num_obs=n()) %>%
  arrange(-total_catch)
  head(mean_region)
```
```{r}
  total_species_pre_1900 <- catch_long %>%
    filter(Year < 1900) %>%
    group_by(Species) %>%
    summarize(total = sum(catch)) %>%
    arrange(desc(total))
  head(total_species_pre_1900)
```


# Join to a region table
```{r}
  region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"), stringsAsFactors = F) %>%
    select(code, mgmtArea)
  head(region_defs)
```
```{r}
  catch_joined <- left_join(catch_long, region_defs, 
                            by = c("Region" = "code"))
  head(catch_joined)
```
```{r}
  site_codes <- data.frame(site=c("HAW-100",
                                  "HAW-101",
                                  "OAH-102",
                                  "OAH-103",
                                  "MAI-100"),
                           stringsAsFactors = F)
```
separate island and site number string 'separate'
```{r}
  site_codes_split <- site_codes %>%
    separate(site, into=c("island", "site_num"), sep="-", remove=F) %>%
    unite(col=new_site, island, site_num, sep="_")
  site_codes_split
```

