---
title: "Plotting"
author: "Jian Li"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(DT)
  library(leaflet)
  library(scales)
```
# Obtain the file 
Read the data file from online repository
```{r}
  data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error = function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        write.csv(esc, "data/escapement.csv", row.names=F)
        return(esc)
    }
)
head(esc)
```

Calculate the total escapement by Species, Region, Year
  Only for Sockeye, Chinook, Coho, Pink, Chum
```{r}
  escapement <- esc %>%
    filter(Species %in% c("Sockeye", "Chinook", "Coho", "Pink", "Chum")) %>%
    separate(col=sampleDate, into=c("Year", "Month", "Day"), sep="-") %>%
    mutate(Year=as.numeric(Year)) %>%
    group_by(Species, SASAP.Region, Year) %>%
    summarize(esc_count = sum(DailyCount))
  escapement
```

Practice on ggplot
```{r}
  ggplot(data=escapement, mapping=aes(x=Species, y=esc_count)) +
    geom_col(fill="blue")
```

```{r}
  ggplot(data=escapement, mapping=aes(x=Species, y=esc_count, fill=SASAP.Region)) +
    geom_col()
```

```{r}

  my_theme <- theme_bw() + theme(legend.position = "bottom")
  escapement %>%
    filter(SASAP.Region=="Kodiak") %>%
    ggplot(mapping=aes(x=Year, y=esc_count, color=Species)) + 
      geom_line() +
      geom_point() +
      scale_y_continuous(labels = comma) +
      ylab("Escapement") +
      ggtitle("Kodiak Salmon Escapement") +
      my_theme
```

```{r, fig.height = 10, fig.width = 10}
    ggplot(escapement, mapping=aes(x=Year, y=esc_count, color=Species)) + 
      geom_line() +
      geom_point() +
      facet_wrap(~SASAP.Region, ncol=2, scales = "free_y") +
      scale_y_continuous(labels = comma) +
      ylab("Escapement") +
      ggtitle("Kodiak Salmon Escapement") +
      my_theme

    ggsave("test.png", height=10, width=10, units="in", dpi=400)
```

```{r}
  locations <- esc %>%
    distinct(Location, Latitude, Longitude) %>%
    drop_na()
  locations
  datatable(locations)
```

```{r}
  leaflet(locations) %>%
    addTiles() %>%
    addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~Location)
```

```{r}
  leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```

